import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Design System Colors parsed directly from DESIGN.md
        'surface-dim': '#d8dad9',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#002204',
        'inverse-surface': '#2e3130',
        'on-error': '#ffffff',
        'surface': '#f8faf8',
        'on-tertiary-container': '#c7ffc5',
        'inverse-on-surface': '#eff1ef',
        'on-tertiary-fixed-variant': '#07521d',
        'on-secondary-fixed': '#002204',
        'error': '#ba1a1a',
        'surface-container-highest': '#e1e3e1',
        'surface-container-high': '#e6e9e7',
        'background': '#f8faf8',
        'surface-container-low': '#f2f4f2',
        'on-primary-fixed-variant': '#005312',
        'secondary-fixed': '#94f990',
        'on-background': '#191c1b',
        'secondary-fixed-dim': '#78dc77',
        'tertiary': '#1d622b',
        'tertiary-container': '#387b41',
        'surface-bright': '#f8faf8',
        'on-surface-variant': '#40493d',
        'on-secondary-container': '#00731e',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#abf4ac',
        'on-secondary-fixed-variant': '#005313',
        'primary-fixed-dim': '#88d982',
        'error-container': '#ffdad6',
        'secondary-container': '#91f78e',
        'on-surface': '#191c1b',
        'on-error-container': '#93000a',
        'secondary': '#006e1c',
        'outline-variant': '#bfcaba',
        'tertiary-fixed-dim': '#90d792',
        'inverse-primary': '#88d982',
        'surface-variant': '#e1e3e1',
        'surface-container': '#eceeec',
        'on-tertiary-fixed': '#002107',
        'primary-container': '#2e7d32',
        'primary-fixed': '#a3f69c',
        'on-primary-container': '#cbffc2',
        'outline': '#707a6c',
        'surface-tint': '#1b6d24',
        'surface-container-lowest': '#ffffff',
        'primary': '#0d631b',
        
        // Semantic helper shades
        brand: {
          50: '#F0FDF4',
          100: '#DCFCE7',
          200: '#BBF7D0',
          300: '#86EFAC',
          400: '#4ADE80',
          500: '#22C55E',
          600: '#16A34A',
          700: '#15803D',
          800: '#166534',
          900: '#14532D',
          950: '#052E16',
        },
        emerald: {
          50: '#ECFDF5',
          100: '#D1FAE5',
          200: '#A7F3D0',
          300: '#6EE7B7',
          400: '#34D399',
          500: '#10B981',
          600: '#059669',
          700: '#047857',
          800: '#065F46',
          900: '#064E3B',
        },
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1280px',
        'section-gap': '80px',
      },
      fontFamily: {
        headline: ['var(--font-comfortaa)', 'Comfortaa', 'sans-serif'],
        body: ['var(--font-hanken)', 'Helvetica Now', 'Helvetica', 'Arial', 'sans-serif'],
        'headline-xl': ['var(--font-comfortaa)', 'Comfortaa', 'sans-serif'],
        'headline-lg': ['var(--font-comfortaa)', 'Comfortaa', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-comfortaa)', 'Comfortaa', 'sans-serif'],
        'body-lg': ['var(--font-hanken)', 'Helvetica Now', 'Helvetica', 'Arial', 'sans-serif'],
        'body-md': ['var(--font-hanken)', 'Helvetica Now', 'Helvetica', 'Arial', 'sans-serif'],
        'label-md': ['var(--font-hanken)', 'Helvetica Now', 'Helvetica', 'Arial', 'sans-serif'],
        'label-sm': ['var(--font-hanken)', 'Helvetica Now', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'soft-sm': '0 2px 8px rgba(46, 125, 50, 0.06)',
        'soft-md': '0 4px 20px rgba(46, 125, 50, 0.08)',
        'soft-lg': '0 10px 30px rgba(46, 125, 50, 0.12)',
        'soft-hover': '0 14px 34px rgba(13, 99, 27, 0.16)',
      },
      animation: {
        'spin-slow': 'spin 30s linear infinite',
        'spin-reverse': 'spin 40s linear infinite reverse',
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 4s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
